language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "vasilenkosergey-github"

jdk:
  - oraclejdk8

before_install:
  - curl -LO https://bitbucket.org/SergeyVasilenko/remedy/downloads/arpluginsvr-9.1.4.pom
  - curl -LO https://bitbucket.org/SergeyVasilenko/remedy/downloads/arpluginsvr-9.1.4.jar
  - mvn install:install-file  -Dfile=arpluginsvr-9.1.4.jar -DpomFile=arpluginsvr-9.1.4.pom

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'